### ISSUE TITLE
OpenVSX support

### ISSUE THREAD

**Issue by dixiedream** [oliversturm/vscode-fix-json#1]
Please upload your extension to openVSX as my Arch installation stop finding it after the marketplace switch.

Thanks

**Comment by oliversturm** [comment]
My apologies - GitHub seems to have trouble with the idea that I should be notified when there are issues in my repos.

I'll check into OpenVSX. Having used Arch myself for a long time, I don't understand the problem though - my VS Code always found extensions, mine and others, without trouble. If you could point me to the "why we need OpenVSX" page, that would be great.

**Comment by dixiedream** [comment]
I was using the official repo VSCode version (the open source version), switched to the AUR version (the Microsoft one) and everything went back to normal.
