### ISSUE TITLE
Request: Format / Fix on save

### ISSUE THREAD

**Issue by katerlouis** [oliversturm/vscode-fix-json#2]
I must be missing something, but why can't VSCode autofix a trailing comma when it already recognizes and declares it visually as an error?

Anyway: thank you for your plug in (although I'm confused to why vscode doesn't do this out of the box) – 

I'm wondering if there's a way to always run it on save?

Thanks!

**Comment by mckeed** [comment]
You can put this in settings.json:

```
    "[json]": {
        "editor.codeActionsOnSave": [
            "fixJson.fix",
            "source.formatDocument"
        ]
    },
```

**Comment by oliversturm** [comment]
My apologies - GitHub seems to have trouble with the idea that I should be notified when there are issues in my repos. 

I notice every now and then than VS Code's built-in handling of invalid JSON code improves over time. However, I still use Fix JSON sometimes, mostly when I don't want to rely on the "standard" feature set - in those cases I'm more likely to explicitly trigger execution manually. But of course the configuration described my @mckeed should work.
